
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Huanyuan2.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 0
          max-wait: 5s
server:
  servlet:
    context-path: /dev-api
resume:
  selenium:
    driver-path: D:/driver/chromedriver-win64/chromedriver.exe
    arguments:
      - --headless=new
      - --disable-gpu
      - --window-size=1280,2000
    url: http://localhost:3000
